[package]
name = "teehee"
version = "0.1.0"
authors = ["Gskartwii <ahannula4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.15.0"
crossterm = "0.17.5"
xi-rope = "0.3.0"
